style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/sehal-comparative/change-log-test

jira:
  info:
    username: Sehal Sein
    token: tjJoN6cbQaIdRaIyjmS08D3A
    url: https://sehal-comp.atlassian.net/jira/
  issue:
    type_maps:
      Task: fix
      Story: feat
    description_pattern: "<changelog>(.*)</changelog>"

options:
  commits:
    filters:
      Type:
        - feat
        - fix
        - perf
        - refactor
  commit_groups:
    title_maps:
      feat: Features
      fix: Fixes
      perf: Performance Improvements
      refactor: Code Refactoring
  header:
    # pattern: "^(?:(\\w*)|(?:\\[(.*)\\])?)\\:\\s(.*)$"
    # pattern_maps:
    #   - Type
    #   - JiraIssueID
    #   - Subject
    pattern: "^(?:(\\w*)|(?:\\[(.*)\\])?)(?:\\(([\\w\\$\\.\\-\\*\\s]*)\\))?\\:\\s(.*)$"
    pattern_maps:
      - Type
      - JiraIssueID
      - Scope
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE